name: message-depoly

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main
        path: ./

    - name: Mkdir public
      run: mkdir public

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        
    - name: Build for web 
      run: |
        cd example
        flutter build web --release

    - name: Copy to public
      run: |
        cp -r example/build/web/* public/

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        token: ${{ secrets.DEPOLY_TOKEN }}
        BRANCH: depoly
        FOLDER: public